basePath: /
definitions:
  app.loginReq:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  app.loginResp:
    properties:
      accesstoken:
        type: string
      expiresin:
        type: integer
      login:
        type: string
      tokentype:
        type: string
      username:
        type: string
    type: object
  app.registerReq:
    properties:
      login:
        type: string
      name:
        type: string
      pass:
        type: string
    type: object
  app.registerResp:
    properties:
      ok:
        type: boolean
    type: object
  ds.Reagent:
    properties:
      description:
        type: string
      formula:
        type: string
      id:
        type: integer
      img:
        type: string
      name:
        type: string
      temperature:
        type: number
      video:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
  description: API with JWT Auth
  license:
    name: AS IS
  title: Lab4 API
  version: "1.0"
paths:
  /api/reagents:
    get:
      description: Публичный метод чтения данных
      parameters:
      - description: Поиск
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Reagent'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Список реагентов
      tags:
      - reagents
  /auth/login:
    post:
      consumes:
      - application/json
      description: JWT, accesstoken
      parameters:
      - description: login request
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/app.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.loginResp'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: JWT
      tags:
      - auth
  /auth/logout:
    post:
      description: JWT blacklist Redis
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Blacklist JWT
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: register request
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/app.registerReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.registerResp'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: 'Type "Bearer" followed by a space and JWT token. Example: "Bearer
      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
